# Example YAML to get you started quickly.
# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'

# This is your document metadata
info:
  title: GRIP Rest API
  description: GRIP as a Service
  version: "0.1.0"

schemes:
  - http
  - https

produces:
  - application/json
#  - text/html

# Describe your paths here
paths:
  # This is a path endpoint. Change it.
  /persons:
    # This is a HTTP operation
    get:
      # Describe this verb here. Note: you can use markdown
      description: |
        Gets `Person` objects.
        Optional query param of **size** determines
        size of returned array
      # This is array of GET operation parameters:
      parameters:
        # An example parameter that is in query and is required
        -
          name: size
          in: query
          description: Size of array
          required: true
          type: number
          format: double
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successful response
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            title: ArrayOfPersons
            type: array
            $ref: '#/definitions/Person'
  /steps:
    get:
      description: |
        Gets `Step` objects
      parameters:
        -
          name: index
          in: query
          required: false
          type: number
          format: integer
      responses:
        200:
          description: Successful response
          schema:
            title: ArrayOfSteps
            type: array
            $ref: '#/definitions/Step'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'


definitions:
  Person:
    type: object
    properties:
      name:
        type: string
      single:
        type: boolean
  Step:
    type: object
    properties:
      name:
        type: string
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
